# images/hopper-vm/config/supervisord.conf
[supervisord]
nodaemon=false
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D -e
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/sshd.err.log
stdout_logfile=/var/log/supervisor/sshd.out.log

[program:code-server]
command=/usr/bin/code-server --config /root/.config/code-server/config.yaml --base-path /api/pods/%(ENV_POD_ID)s/vscode /workspace
autostart=true
autorestart=true
environment=HOME="/root",USER="root"
stderr_logfile=/var/log/supervisor/code-server.err.log
stdout_logfile=/var/log/supervisor/code-server.out.log
