# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto.hopper.billing.v1 import billing_pb2 as hopper_dot_billing_dot_v1_dot_billing__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hopper/billing/v1/billing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BillingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeductCredits = channel.unary_unary(
                '/hopper.billing.v1.BillingService/DeductCredits',
                request_serializer=hopper_dot_billing_dot_v1_dot_billing__pb2.DeductRequest.SerializeToString,
                response_deserializer=hopper_dot_billing_dot_v1_dot_billing__pb2.DeductResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/hopper.billing.v1.BillingService/GetBalance',
                request_serializer=hopper_dot_billing_dot_v1_dot_billing__pb2.AccountId.SerializeToString,
                response_deserializer=hopper_dot_billing_dot_v1_dot_billing__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.StreamUsage = channel.unary_stream(
                '/hopper.billing.v1.BillingService/StreamUsage',
                request_serializer=hopper_dot_billing_dot_v1_dot_billing__pb2.AccountId.SerializeToString,
                response_deserializer=hopper_dot_billing_dot_v1_dot_billing__pb2.UsageEvent.FromString,
                _registered_method=True)


class BillingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeductCredits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeductCredits': grpc.unary_unary_rpc_method_handler(
                    servicer.DeductCredits,
                    request_deserializer=hopper_dot_billing_dot_v1_dot_billing__pb2.DeductRequest.FromString,
                    response_serializer=hopper_dot_billing_dot_v1_dot_billing__pb2.DeductResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=hopper_dot_billing_dot_v1_dot_billing__pb2.AccountId.FromString,
                    response_serializer=hopper_dot_billing_dot_v1_dot_billing__pb2.BalanceResponse.SerializeToString,
            ),
            'StreamUsage': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUsage,
                    request_deserializer=hopper_dot_billing_dot_v1_dot_billing__pb2.AccountId.FromString,
                    response_serializer=hopper_dot_billing_dot_v1_dot_billing__pb2.UsageEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hopper.billing.v1.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hopper.billing.v1.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeductCredits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hopper.billing.v1.BillingService/DeductCredits',
            hopper_dot_billing_dot_v1_dot_billing__pb2.DeductRequest.SerializeToString,
            hopper_dot_billing_dot_v1_dot_billing__pb2.DeductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hopper.billing.v1.BillingService/GetBalance',
            hopper_dot_billing_dot_v1_dot_billing__pb2.AccountId.SerializeToString,
            hopper_dot_billing_dot_v1_dot_billing__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hopper.billing.v1.BillingService/StreamUsage',
            hopper_dot_billing_dot_v1_dot_billing__pb2.AccountId.SerializeToString,
            hopper_dot_billing_dot_v1_dot_billing__pb2.UsageEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
