# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hopper/billing/v1/billing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hopper/billing/v1/billing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fhopper/billing/v1/billing.proto\x12\x11hopper.billing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n\tAccountId\x12\n\n\x02id\x18\x01 \x01(\t\"a\n\rDeductRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x0e\n\x06pod_id\x18\x04 \x01(\t\x12\x0c\n\x04plan\x18\x05 \x01(\t\"M\n\x0e\x44\x65\x64uctResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x19\n\x11remaining_balance\x18\x02 \x01(\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\"a\n\x0f\x42\x61lanceResponse\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\x12)\n\x05\x61s_of\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"}\n\nUsageEvent\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0e\n\x06pod_id\x18\x04 \x01(\t\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x84\x02\n\x0e\x42illingService\x12T\n\rDeductCredits\x12 .hopper.billing.v1.DeductRequest\x1a!.hopper.billing.v1.DeductResponse\x12N\n\nGetBalance\x12\x1c.hopper.billing.v1.AccountId\x1a\".hopper.billing.v1.BalanceResponse\x12L\n\x0bStreamUsage\x12\x1c.hopper.billing.v1.AccountId\x1a\x1d.hopper.billing.v1.UsageEvent0\x01\x42?Z=github.com/hopper/orchestrator/api/proto/billing/v1;billingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hopper.billing.v1.billing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/hopper/orchestrator/api/proto/billing/v1;billingv1'
  _globals['_ACCOUNTID']._serialized_start=87
  _globals['_ACCOUNTID']._serialized_end=110
  _globals['_DEDUCTREQUEST']._serialized_start=112
  _globals['_DEDUCTREQUEST']._serialized_end=209
  _globals['_DEDUCTRESPONSE']._serialized_start=211
  _globals['_DEDUCTRESPONSE']._serialized_end=288
  _globals['_BALANCERESPONSE']._serialized_start=290
  _globals['_BALANCERESPONSE']._serialized_end=387
  _globals['_USAGEEVENT']._serialized_start=389
  _globals['_USAGEEVENT']._serialized_end=514
  _globals['_BILLINGSERVICE']._serialized_start=517
  _globals['_BILLINGSERVICE']._serialized_end=777
# @@protoc_insertion_point(module_scope)
