apiVersion: v1
kind: Namespace
metadata:
  name: hopper-system
  labels:
    app.kubernetes.io/part-of: hopper
---
apiVersion: v1
kind: Namespace
metadata:
  name: hopper-pods
  labels:
    app.kubernetes.io/part-of: hopper
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
