# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto.hopper.pod.v1 import pod_pb2 as hopper_dot_pod_dot_v1_dot_pod__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hopper/pod/v1/pod_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PodOrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePod = channel.unary_unary(
                '/hopper.pod.v1.PodOrchestrator/CreatePod',
                request_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.CreatePodRequest.SerializeToString,
                response_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodStatus.FromString,
                _registered_method=True)
        self.TerminatePod = channel.unary_unary(
                '/hopper.pod.v1.PodOrchestrator/TerminatePod',
                request_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.SerializeToString,
                response_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.TerminateResponse.FromString,
                _registered_method=True)
        self.GetPodStatus = channel.unary_unary(
                '/hopper.pod.v1.PodOrchestrator/GetPodStatus',
                request_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.SerializeToString,
                response_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodStatus.FromString,
                _registered_method=True)
        self.StreamMetrics = channel.unary_stream(
                '/hopper.pod.v1.PodOrchestrator/StreamMetrics',
                request_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.SerializeToString,
                response_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.VmMetrics.FromString,
                _registered_method=True)
        self.WatchPodStatus = channel.unary_stream(
                '/hopper.pod.v1.PodOrchestrator/WatchPodStatus',
                request_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.SerializeToString,
                response_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodStatus.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/hopper.pod.v1.PodOrchestrator/ListNodes',
                request_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.ListNodesResponse.FromString,
                _registered_method=True)


class PodOrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminatePod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPodStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchPodStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PodOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePod': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePod,
                    request_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.CreatePodRequest.FromString,
                    response_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodStatus.SerializeToString,
            ),
            'TerminatePod': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminatePod,
                    request_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.FromString,
                    response_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.TerminateResponse.SerializeToString,
            ),
            'GetPodStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPodStatus,
                    request_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.FromString,
                    response_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodStatus.SerializeToString,
            ),
            'StreamMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.FromString,
                    response_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.VmMetrics.SerializeToString,
            ),
            'WatchPodStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchPodStatus,
                    request_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.FromString,
                    response_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.PodStatus.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=hopper_dot_pod_dot_v1_dot_pod__pb2.ListNodesRequest.FromString,
                    response_serializer=hopper_dot_pod_dot_v1_dot_pod__pb2.ListNodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hopper.pod.v1.PodOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hopper.pod.v1.PodOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PodOrchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hopper.pod.v1.PodOrchestrator/CreatePod',
            hopper_dot_pod_dot_v1_dot_pod__pb2.CreatePodRequest.SerializeToString,
            hopper_dot_pod_dot_v1_dot_pod__pb2.PodStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminatePod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hopper.pod.v1.PodOrchestrator/TerminatePod',
            hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.SerializeToString,
            hopper_dot_pod_dot_v1_dot_pod__pb2.TerminateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPodStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hopper.pod.v1.PodOrchestrator/GetPodStatus',
            hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.SerializeToString,
            hopper_dot_pod_dot_v1_dot_pod__pb2.PodStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hopper.pod.v1.PodOrchestrator/StreamMetrics',
            hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.SerializeToString,
            hopper_dot_pod_dot_v1_dot_pod__pb2.VmMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchPodStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hopper.pod.v1.PodOrchestrator/WatchPodStatus',
            hopper_dot_pod_dot_v1_dot_pod__pb2.PodId.SerializeToString,
            hopper_dot_pod_dot_v1_dot_pod__pb2.PodStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hopper.pod.v1.PodOrchestrator/ListNodes',
            hopper_dot_pod_dot_v1_dot_pod__pb2.ListNodesRequest.SerializeToString,
            hopper_dot_pod_dot_v1_dot_pod__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
